Revive area labels counts [MAP-661]
commonknowledge/mapped pull request #148
Opened 2024-12-09 15:38 UTC by janbaykara

Follows on from #147.

- Re-adds area names and labels which was in the old map
- Adds some stronger typing the to the Boundary Analytics hook return data

2024-12-09 15:58 UTC, ev-sc requested changes
Thanks for bringing these back!
Some comments:

- The labels are colliding/overlapping. I think they need to be scaled to something like maximum half the width of the boundary or something like that. You'll just need to zoom in further to read them. Or isn't there a mapbox setting to hide collisions?

- I don't think the scaling of text size based on the numerical value is adding anything. Bigger numbers are already bigger: two-digit numbers are bigger than single-digit numbers; three-digit numbers and bigger than two-digit numbers etc...

2024-12-09 16:26 UTC, janbaykara commented
I disagree with this:

> I don't think the scaling of numeric label text size based on the value is adding anything. Bigger numbers are already bigger: two-digit numbers are bigger than single-digit numbers; three-digit numbers are bigger than two-digit numbers etc...

A series of 1 3 5 3 4 0 100 3 2 5 0 8 2 1 3 8 on a map gets cluttered very quickly, as I found out when I first prototyped the map, which is why I implemented this scaling logic. I can't give you a demo screenshot right now because my local environment is playing up, so if you'd like one I'll generate it tomorrow. But I stand quite strongly opinionated on this from experience.

2024-12-09 16:55 UTC, ev-sc commented
@janbaykara let's merge it for now to get back the functionality, but make it configurable later x

2024-12-09 16:55 UTC, merged

2024-12-10 13:41 UTC, janbaykara commented
Roger, will make a ticket so we don't forget!